user nginx;

worker_processes auto;
pcre_jit on;
error_log ${NGINX_LOGDIR}.log warn;

daemon off; // desactiva el segundo plano de la aplication 


events {
	worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    # -------------------------------------------------------------
    # 1. REDIRECCIÓN DE HTTP A HTTPS
    # -------------------------------------------------------------
    server {
        listen 80;
        listen [::]:80;
        server_name ${DOMAIN_NAME};

        # Redirige permanentemente (301) a la versión HTTPS
        return 301 https://$host$request_uri;
    }

    # -------------------------------------------------------------
    # 2. CONFIGURACIÓN SERVIDOR SEGURO (HTTPS)
    # -------------------------------------------------------------
    server {
        listen ${NGINX_PORT} ssl;
            listen [::]:${NGINX_PORT} ssl;
        server_name ${DOMAIN_NAME};

            # Rutas a los certificados dentro del contenedor
            ssl_certificate ${SSL_PATH}${DOMAIN_NAME}.crt;
            ssl_certificate_key ${SSL_PATH}${DOMAIN_NAME}.key;
            
        # Habilita ambos protocolos (Nginx negociará 1.3 automáticamente si el cliente lo soporta)
        ssl_protocols TLSv1.2 TLSv1.3;

        # Cifrados ultra-seguros para TLS 1.2 (TLS 1.3 los gestiona internamente)
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
        ssl_prefer_server_ciphers on;

        root /var/www/html;
        index index.php index.html index.htm;

        # Optimización de rendimiento
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 1d;
        ssl_session_tickets off;
        }
            location / {
            try_files $uri $uri/ /index.php?$args;
        }
          location ~ \.php$ {
            include fastcgi_params;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass wordpress:9000; # Nombre del servicio en tu docker-compose
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME ${NGINX_BDIR}$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }

        location /health {
            index index.html;
        }
}
